2021-09-30 15:37:37,263: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:39:42,714: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:40:37,434: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 17:04:05,100: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:04:15,449: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:11:58,530: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:12:15,155: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/justice/views.py", line 13, in index
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:12:19,877: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/justice/views.py", line 13, in index
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-10-01 11:28:37,162: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 658, in __init__
    self.args_check(filter_name, filter_func, args)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 717, in args_check
    raise TemplateSyntaxError("%s requires %d arguments, %d provided" %
django.template.exceptions.TemplateSyntaxError: default requires 2 arguments, 1 provided
2021-10-01 11:38:15,749: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'nabil[0]'
2021-10-01 11:50:32,653: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3705, 139652241278720, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 658, in __init__
    self.args_check(filter_name, filter_func, args)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 717, in args_check
    raise TemplateSyntaxError("%s requires %d arguments, %d provided" %
django.template.exceptions.TemplateSyntaxError: string_to_list requires 3 arguments, 2 provided
2021-10-01 11:51:13,153: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3809, 140091600627456, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' ", "' from 'nabil|string_to_list:"clients, adversaires, avocat_adversaire" ", "'
2021-10-01 12:07:26,166: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:09:26,632: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:09:40,840: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:09:46,961: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:10:05,795: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'list[0]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'list[0]'
2021-10-01 12:25:53,742: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '==list.2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==list.2' from '==list.2'
2021-10-01 12:34:18,722: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Internal Server Error: /avocats_adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 251, in justice_avocats_adversaires
    avocats_adv = AvocatAdversaire.objects.annotate(
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1056, in annotate
    clone.query.add_annotation(annotation, alias, is_summary=False)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 999, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None,
  File "/usr/lib/python3/dist-packages/django/contrib/postgres/search.py", line 62, in resolve_expression
    resolved = super().resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/usr/lib/python3/dist-packages/django/db/models/expressions.py", line 603, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/usr/lib/python3/dist-packages/django/db/models/expressions.py", line 514, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1601, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1503, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1419, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'company' into field. Choices are: adresse, cabinet, created_at, email, gsm, id, nom, observation, prenom, sexe, slug, tel, updated_at, ville
2021-10-01 12:34:38,891: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4494, 140369495815936, Internal Server Error: /avocats_adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 258, in justice_avocats_adversaires
    paginator = Paginator(avocats, AVOCAT_ADVERSARIES_PER_PAGE)
NameError: name 'avocats' is not defined
2021-10-01 13:55:30,155: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5268, 140550983964416, Internal Server Error: /avocats_adversaires/create
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 295, in avocat_adversaire_form
    form = AvocatAdversaireForm()
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 76, in __init__
    self.fields['type_adversaire'].widget.attrs['id'] = 'radio-switch-4'
KeyError: 'type_adversaire'
2021-10-01 14:12:26,608: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Internal Server Error: /avocats_adversaires/create
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 315, in avocat_adversaire_form
    print('form.is_valid(): ', form.is_valid())
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 402, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 92, in clean_cabinet
    return self.cleaned_data['cabinet'].upper()
AttributeError: 'NoneType' object has no attribute 'upper'
