2021-09-30 09:47:28,064: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/profile-9.jpg
2021-09-30 09:47:28,078: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295206201088, Not Found: /dist/images/profile-11.jpg
2021-09-30 09:47:28,096: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294972503808, Not Found: /dist/images/profile-12.jpg
2021-09-30 09:47:28,144: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-2.jpg
2021-09-30 09:47:28,269: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294972503808, Not Found: /dist/images/profile-14.jpg
2021-09-30 09:47:28,338: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294955718400, Not Found: /dist/images/profile-2.jpg
2021-09-30 09:47:28,342: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/profile-6.jpg
2021-09-30 09:47:28,349: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295206201088, Not Found: /dist/images/preview-11.jpg
2021-09-30 09:47:28,479: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-9.jpg
2021-09-30 09:47:28,457: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295188367104, Not Found: /dist/images/preview-13.jpg
2021-09-30 09:47:28,768: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294955718400, Not Found: /dist/images/preview-5.jpg
2021-09-30 09:47:28,854: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-15.jpg
2021-09-30 09:47:28,940: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/preview-1.jpg
2021-09-30 09:47:28,975: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295188367104, Not Found: /dist/images/preview-3.jpg
2021-09-30 09:47:29,005: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294972503808, Not Found: /dist/images/preview-8.jpg
2021-09-30 09:47:29,136: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-12.jpg
2021-09-30 09:47:29,161: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294955718400, Not Found: /dist/images/profile-3.jpg
2021-09-30 09:47:29,186: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/profile-4.jpg
2021-09-30 09:47:30,104: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/json/location.json
2021-09-30 09:47:30,785: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:47:39,966: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:47:42,868: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:47:45,798: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/dist/images/profile-9.jpg
2021-09-30 09:48:05,004: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:48:07,027: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/dist/images/profile-9.jpg
2021-09-30 09:49:17,291: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:49:27,468: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:49:33,570: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:49:35,169: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/dist/images/profile-9.jpg
2021-09-30 09:50:59,391: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:53:15,416: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 10:02:22,175: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 10:02:42,987: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 10:02:57,387: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:08:41,888: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808442873600, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:08:41,890: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808366130944, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:08:41,898: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:08:41,905: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808332560128, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:08:41,959: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808340952832, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:08:42,182: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808442873600, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:08:42,415: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808357738240, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:08:42,424: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:08:42,474: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:08:42,483: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808332560128, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:08:42,511: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808357738240, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:08:42,518: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:08:42,589: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:08:42,694: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:08:42,758: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808332560128, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:08:42,778: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808357738240, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:08:42,786: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808442873600, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:08:42,941: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:08:43,889: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/json/location.json
2021-09-30 15:08:45,968: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:09:08,830: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:12:04,345: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:19:21,214: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5414, 140288240899840, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:37:33,916: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:37:37,263: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:37:37,766: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /favicon.ico
2021-09-30 15:39:27,934: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:39:27,995: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:39:28,028: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:39:28,057: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:39:28,123: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:39:28,131: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:39:28,177: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:39:28,207: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:39:28,245: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:39:28,262: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:39:28,277: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:39:28,332: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:39:28,482: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:39:28,601: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:39:28,849: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:39:28,916: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726005982976, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:39:28,957: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139725997590272, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:39:29,104: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:39:29,626: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/json/location.json
2021-09-30 15:39:37,833: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:39:37,847: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:39:37,913: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105905420032, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:39:38,025: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105905420032, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:39:38,033: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:39:38,166: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:39:38,373: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:39:38,425: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105923516160, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:39:38,626: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:39:38,647: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:39:38,712: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:39:38,829: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:39:38,841: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:39:38,898: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105923516160, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:39:38,915: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105905420032, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:39:39,059: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105923516160, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:39:39,067: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:39:39,116: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:39:39,935: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/json/location.json
2021-09-30 15:39:40,338: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:39:42,714: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:40:37,434: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:41:28,408: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:41:28,415: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:41:28,476: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489982469888, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:41:28,491: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:41:28,528: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489965684480, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:41:28,542: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:41:28,644: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:41:28,711: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:41:28,733: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:41:28,781: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489965684480, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:41:28,940: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:41:29,094: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489965684480, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:41:29,140: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:41:29,150: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:41:29,286: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:41:29,298: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:41:29,526: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:41:29,749: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:41:30,473: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/json/location.json
2021-09-30 15:41:46,619: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:41:50,060: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:42:02,600: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:42:20,196: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:43:43,912: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5993, 139964838823680, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:43:45,121: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5993, 139964838823680, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:43:49,700: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5993, 139964838823680, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:45:30,916: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6040, 140184727754496, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:45:36,425: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6040, 140184645531392, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:02:47,394: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:02:51,468: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/2/dist/images/profile-9.jpg
2021-09-30 16:03:16,423: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:03:19,781: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/2/dist/images/profile-9.jpg
2021-09-30 16:03:28,737: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:17:52,468: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:17:58,683: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:49:24,470: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:49:32,743: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:49:51,983: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 16:50:13,491: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:55:46,373: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583348745984, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:56:07,327: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-9.jpg
2021-09-30 16:56:07,503: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-2.jpg
2021-09-30 16:56:07,583: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/profile-12.jpg
2021-09-30 16:56:07,595: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-11.jpg
2021-09-30 16:56:07,683: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-14.jpg
2021-09-30 16:56:07,815: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/preview-13.jpg
2021-09-30 16:56:07,913: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-6.jpg
2021-09-30 16:56:07,809: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-11.jpg
2021-09-30 16:56:07,977: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-9.jpg
2021-09-30 16:56:07,987: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/preview-2.jpg
2021-09-30 16:56:08,076: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-5.jpg
2021-09-30 16:56:08,150: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-15.jpg
2021-09-30 16:56:08,127: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/preview-1.jpg
2021-09-30 16:56:08,166: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583348745984, Not Found: /dist/images/preview-8.jpg
2021-09-30 16:56:08,303: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/preview-3.jpg
2021-09-30 16:56:08,347: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-12.jpg
2021-09-30 16:56:08,393: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-3.jpg
2021-09-30 16:56:08,413: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/profile-4.jpg
2021-09-30 16:56:09,052: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/json/location.json
2021-09-30 16:56:09,807: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/profile-9.jpg
2021-09-30 16:56:09,827: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-2.jpg
2021-09-30 16:56:09,872: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-12.jpg
2021-09-30 16:56:09,897: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583246743296, Not Found: /dist/images/preview-5.jpg
2021-09-30 16:56:09,879: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/profile-11.jpg
2021-09-30 16:56:09,923: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-2.jpg
2021-09-30 16:56:10,135: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-15.jpg
2021-09-30 16:56:10,163: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-1.jpg
2021-09-30 16:56:10,175: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-9.jpg
2021-09-30 16:56:10,179: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-8.jpg
2021-09-30 16:56:10,205: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-6.jpg
2021-09-30 16:56:10,243: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583246743296, Not Found: /dist/images/preview-11.jpg
2021-09-30 16:56:10,247: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/profile-14.jpg
2021-09-30 16:56:10,253: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-13.jpg
2021-09-30 16:56:10,261: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-3.jpg
2021-09-30 16:56:10,351: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/preview-12.jpg
2021-09-30 16:56:10,363: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/profile-3.jpg
2021-09-30 16:56:10,417: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/profile-4.jpg
2021-09-30 16:56:11,117: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/json/location.json
2021-09-30 16:56:12,918: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:56:44,951: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:03:39,732: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:03:47,812: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/Casablanca/search/dist/images/profile-9.jpg
2021-09-30 17:03:52,085: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:03:59,526: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:04:05,100: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:04:15,449: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:05:22,798: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:05:30,618: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:05:35,867: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:05:38,296: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:07:45,725: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:07:51,229: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:09:27,811: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:09:59,367: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:10:41,833: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:10:43,609: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:11:58,530: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:12:15,155: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/justice/views.py", line 13, in index
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:12:19,877: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/justice/views.py", line 13, in index
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:17:32,292: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348673120000, Not Found: /dist/images/profile-9.jpg
2021-09-30 17:17:32,380: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/profile-2.jpg
2021-09-30 17:17:32,398: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/profile-12.jpg
2021-09-30 17:17:32,575: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-5.jpg
2021-09-30 17:17:32,581: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/profile-11.jpg
2021-09-30 17:17:32,590: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-2.jpg
2021-09-30 17:17:32,679: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-1.jpg
2021-09-30 17:17:32,762: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-9.jpg
2021-09-30 17:17:32,782: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348698298112, Not Found: /dist/images/profile-6.jpg
2021-09-30 17:17:32,762: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/preview-15.jpg
2021-09-30 17:17:32,874: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/images/preview-11.jpg
2021-09-30 17:17:33,065: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/images/profile-14.jpg
2021-09-30 17:17:33,075: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/preview-13.jpg
2021-09-30 17:17:33,084: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348698298112, Not Found: /dist/images/preview-8.jpg
2021-09-30 17:17:33,365: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-3.jpg
2021-09-30 17:17:33,450: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348715083520, Not Found: /dist/images/preview-12.jpg
2021-09-30 17:17:33,643: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348698298112, Not Found: /dist/images/profile-3.jpg
2021-09-30 17:17:33,809: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/images/profile-4.jpg
2021-09-30 17:17:34,565: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/json/location.json
2021-09-30 17:17:35,006: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:17:53,223: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:18:11,111: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:19:44,272: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:19:49,710: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:20:28,584: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:22:55,504: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:22:59,946: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 17:23:18,514: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:23:57,531: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:24:04,424: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:33:21,542: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-2.jpg
2021-10-01 10:33:21,569: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-9.jpg
2021-10-01 10:33:21,600: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-12.jpg
2021-10-01 10:33:21,654: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/profile-11.jpg
2021-10-01 10:33:21,663: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-2.jpg
2021-10-01 10:33:21,684: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666109142784, Not Found: /dist/images/preview-5.jpg
2021-10-01 10:33:21,688: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666100750080, Not Found: /dist/images/preview-15.jpg
2021-10-01 10:33:21,895: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666109142784, Not Found: /dist/images/preview-1.jpg
2021-10-01 10:33:21,901: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/preview-9.jpg
2021-10-01 10:33:21,920: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-11.jpg
2021-10-01 10:33:22,007: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666100750080, Not Found: /dist/images/preview-13.jpg
2021-10-01 10:33:22,037: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666109142784, Not Found: /dist/images/profile-14.jpg
2021-10-01 10:33:22,106: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-6.jpg
2021-10-01 10:33:22,134: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666109142784, Not Found: /dist/images/preview-3.jpg
2021-10-01 10:33:22,135: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-8.jpg
2021-10-01 10:33:22,198: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666100750080, Not Found: /dist/images/preview-12.jpg
2021-10-01 10:33:22,234: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666100750080, Not Found: /dist/images/profile-4.jpg
2021-10-01 10:33:22,238: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-3.jpg
2021-10-01 10:33:23,536: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/json/location.json
2021-10-01 10:33:24,562: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:41:25,942: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:41:28,699: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:42:23,832: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:43:07,582: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:44:20,655: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:52:13,841: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:53:15,567: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:53:30,774: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 10:53:36,429: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-12.jpg
2021-10-01 10:53:36,484: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/profile-9.jpg
2021-10-01 10:53:36,534: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-2.jpg
2021-10-01 10:53:36,543: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-11.jpg
2021-10-01 10:53:36,555: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-5.jpg
2021-10-01 10:53:36,582: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-2.jpg
2021-10-01 10:53:36,803: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-1.jpg
2021-10-01 10:53:36,676: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-15.jpg
2021-10-01 10:53:36,917: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-13.jpg
2021-10-01 10:53:36,955: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-9.jpg
2021-10-01 10:53:37,014: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-8.jpg
2021-10-01 10:53:37,134: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-3.jpg
2021-10-01 10:53:37,201: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-14.jpg
2021-10-01 10:53:37,225: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-12.jpg
2021-10-01 10:53:37,372: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-6.jpg
2021-10-01 10:53:37,416: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-11.jpg
2021-10-01 10:53:37,547: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-4.jpg
2021-10-01 10:53:37,553: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-3.jpg
2021-10-01 10:53:38,525: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/json/location.json
2021-10-01 10:54:44,118: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-12.jpg
2021-10-01 10:54:44,180: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-11.jpg
2021-10-01 10:54:44,309: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-2.jpg
2021-10-01 10:54:44,184: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-9.jpg
2021-10-01 10:54:44,438: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-15.jpg
2021-10-01 10:54:44,231: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-2.jpg
2021-10-01 10:54:44,479: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-5.jpg
2021-10-01 10:54:44,506: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-1.jpg
2021-10-01 10:54:44,567: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-9.jpg
2021-10-01 10:54:44,580: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-8.jpg
2021-10-01 10:54:44,616: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-3.jpg
2021-10-01 10:54:44,679: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-13.jpg
2021-10-01 10:54:44,689: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-12.jpg
2021-10-01 10:54:44,741: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-14.jpg
2021-10-01 10:54:44,755: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-6.jpg
2021-10-01 10:54:44,920: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-11.jpg
2021-10-01 10:54:44,964: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-3.jpg
2021-10-01 10:54:45,068: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-4.jpg
2021-10-01 10:54:46,176: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/json/location.json
2021-10-01 10:55:34,490: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-9.jpg
2021-10-01 10:55:34,504: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-12.jpg
2021-10-01 10:55:34,514: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-2.jpg
2021-10-01 10:55:34,519: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-11.jpg
2021-10-01 10:55:34,522: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-5.jpg
2021-10-01 10:55:34,525: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/preview-2.jpg
2021-10-01 10:55:34,591: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/preview-15.jpg
2021-10-01 10:55:34,607: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-1.jpg
2021-10-01 10:55:34,616: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-9.jpg
2021-10-01 10:55:34,624: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-8.jpg
2021-10-01 10:55:34,654: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-3.jpg
2021-10-01 10:55:34,730: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-13.jpg
2021-10-01 10:55:34,786: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-12.jpg
2021-10-01 10:55:34,791: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/profile-14.jpg
2021-10-01 10:55:34,879: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-6.jpg
2021-10-01 10:55:34,885: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-11.jpg
2021-10-01 10:55:34,889: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-3.jpg
2021-10-01 10:55:34,915: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-4.jpg
2021-10-01 10:55:35,869: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/json/location.json
2021-10-01 10:58:48,407: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-2.jpg
2021-10-01 10:58:48,436: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-9.jpg
2021-10-01 10:58:48,455: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-12.jpg
2021-10-01 10:58:48,479: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/profile-11.jpg
2021-10-01 10:58:48,506: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-2.jpg
2021-10-01 10:58:48,517: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-5.jpg
2021-10-01 10:58:48,539: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-15.jpg
2021-10-01 10:58:48,575: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-1.jpg
2021-10-01 10:58:48,634: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-9.jpg
2021-10-01 10:58:48,667: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-8.jpg
2021-10-01 10:58:48,700: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-13.jpg
2021-10-01 10:58:48,725: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-12.jpg
2021-10-01 10:58:48,752: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/preview-11.jpg
2021-10-01 10:58:48,775: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-3.jpg
2021-10-01 10:58:48,790: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-14.jpg
2021-10-01 10:58:48,807: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-6.jpg
2021-10-01 10:58:48,813: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-3.jpg
2021-10-01 10:58:48,819: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-4.jpg
2021-10-01 10:58:49,491: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/json/location.json
2021-10-01 11:02:10,791: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:02:10,887: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:02:10,976: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:02:11,098: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:02:11,102: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:02:11,216: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:02:11,341: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:02:11,387: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:02:11,407: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:02:11,430: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:02:11,474: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:02:11,513: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:02:11,631: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:02:11,804: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:02:11,808: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:02:11,859: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:02:11,930: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:02:11,955: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:02:12,864: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/json/location.json
2021-10-01 11:03:38,042: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:03:38,107: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:03:38,135: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:03:38,310: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:03:38,352: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:03:38,193: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:03:38,371: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:03:38,401: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:03:38,492: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:03:38,562: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:03:38,542: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:03:38,697: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:03:38,707: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:03:38,841: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:03:38,903: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:03:38,954: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:03:39,063: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:03:39,037: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:03:40,164: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/json/location.json
2021-10-01 11:03:44,599: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:03:44,612: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:03:44,615: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:03:44,625: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:03:44,705: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:03:44,787: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:03:44,969: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:03:44,947: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:03:45,049: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:03:45,168: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:03:45,367: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:03:45,379: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:03:45,384: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:03:45,424: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:03:45,539: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:03:45,582: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:03:45,614: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666134845184, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:03:45,630: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:03:46,589: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/json/location.json
2021-10-01 11:05:13,201: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:05:13,244: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:05:13,257: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:05:13,305: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:05:13,388: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:05:13,431: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:05:13,500: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:05:13,654: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:05:13,516: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:05:13,550: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:05:13,518: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:05:13,773: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:05:13,799: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:05:13,863: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:05:13,913: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:05:14,033: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:05:14,071: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:05:14,052: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:05:15,302: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666143237888, Not Found: /dist/json/location.json
2021-10-01 11:05:48,424: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:05:48,513: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:05:48,628: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:05:48,634: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:05:48,853: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:05:48,887: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:05:48,895: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:05:49,003: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:05:49,013: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:05:49,106: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:05:49,214: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:05:49,400: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:05:49,470: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666362189568, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:05:49,490: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:05:49,508: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:05:49,532: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:05:49,589: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:05:49,606: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:05:50,324: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/json/location.json
2021-10-01 11:06:10,478: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:06:10,505: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:06:10,551: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:06:10,558: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:06:10,606: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:06:10,621: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:06:10,628: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:06:10,639: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:06:10,676: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:06:10,709: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:06:10,740: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:06:10,757: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:06:10,768: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:06:10,802: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:06:10,806: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:06:10,830: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:06:10,871: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:06:10,964: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:06:11,799: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/json/location.json
2021-10-01 11:06:50,125: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-9.jpg
2021-10-01 11:06:50,135: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-12.jpg
2021-10-01 11:06:50,141: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-2.jpg
2021-10-01 11:06:50,158: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-11.jpg
2021-10-01 11:06:50,171: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-2.jpg
2021-10-01 11:06:50,189: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-5.jpg
2021-10-01 11:06:50,215: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-15.jpg
2021-10-01 11:06:50,231: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-1.jpg
2021-10-01 11:06:50,243: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-9.jpg
2021-10-01 11:06:50,286: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/preview-8.jpg
2021-10-01 11:06:50,297: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-3.jpg
2021-10-01 11:06:50,317: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-13.jpg
2021-10-01 11:06:50,323: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/preview-12.jpg
2021-10-01 11:06:50,330: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666370844416, Not Found: /dist/images/profile-14.jpg
2021-10-01 11:06:50,335: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-6.jpg
2021-10-01 11:06:50,356: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666151630592, Not Found: /dist/images/preview-11.jpg
2021-10-01 11:06:50,392: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666125928192, Not Found: /dist/images/profile-3.jpg
2021-10-01 11:06:50,467: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/images/profile-4.jpg
2021-10-01 11:06:51,367: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /dist/json/location.json
2021-10-01 11:06:56,266: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:24:41,240: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:24:44,072: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:24:49,254: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:24:51,354: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:28:37,162: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 658, in __init__
    self.args_check(filter_name, filter_func, args)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 717, in args_check
    raise TemplateSyntaxError("%s requires %d arguments, %d provided" %
django.template.exceptions.TemplateSyntaxError: default requires 2 arguments, 1 provided
2021-10-01 11:28:37,803: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /favicon.ico
2021-10-01 11:30:12,098: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:30:48,016: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:38:15,749: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2153, 140666117535488, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'nabil[0]'
2021-10-01 11:48:49,195: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3705, 139652268029696, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:48:52,452: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3705, 139652268029696, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:48:59,013: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3705, 139652241278720, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:50:32,653: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3705, 139652241278720, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 658, in __init__
    self.args_check(filter_name, filter_func, args)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 717, in args_check
    raise TemplateSyntaxError("%s requires %d arguments, %d provided" %
django.template.exceptions.TemplateSyntaxError: string_to_list requires 3 arguments, 2 provided
2021-10-01 11:51:13,153: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3809, 140091600627456, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' ", "' from 'nabil|string_to_list:"clients, adversaires, avocat_adversaire" ", "'
2021-10-01 11:51:39,284: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3809, 140091600627456, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:52:38,377: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3809, 140091600627456, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 11:59:11,544: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:07:26,166: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:09:26,632: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:09:40,840: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:09:46,961: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 204, in expression
    left = t.led(left, self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 53, in led
    self.second = parser.expression(bp)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 22, in nud
    raise parser.error_class(
django.template.exceptions.TemplateSyntaxError: Not expecting 'in' in this position in if tag.
2021-10-01 12:10:05,795: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'list[0]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'list[0]'
2021-10-01 12:11:41,946: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:11:46,220: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /dist/images/profile-12.jpg
2021-10-01 12:11:46,248: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/profile-2.jpg
2021-10-01 12:11:46,256: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108724082432, Not Found: /dist/images/profile-9.jpg
2021-10-01 12:11:46,313: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /dist/images/preview-5.jpg
2021-10-01 12:11:46,319: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/preview-2.jpg
2021-10-01 12:11:46,365: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/profile-11.jpg
2021-10-01 12:11:46,377: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/preview-15.jpg
2021-10-01 12:11:46,382: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /dist/images/preview-1.jpg
2021-10-01 12:11:46,403: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/preview-9.jpg
2021-10-01 12:11:46,433: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/preview-8.jpg
2021-10-01 12:11:46,440: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /dist/images/preview-3.jpg
2021-10-01 12:11:46,480: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/preview-12.jpg
2021-10-01 12:11:46,486: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/preview-13.jpg
2021-10-01 12:11:46,496: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /dist/images/profile-14.jpg
2021-10-01 12:11:46,523: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/preview-11.jpg
2021-10-01 12:11:46,533: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/profile-6.jpg
2021-10-01 12:11:46,538: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/profile-3.jpg
2021-10-01 12:11:46,559: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108734572288, Not Found: /dist/images/profile-4.jpg
2021-10-01 12:11:47,461: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/json/location.json
2021-10-01 12:11:50,331: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:11:52,405: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:11:53,837: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:25:53,742: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Internal Server Error: /clients/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '==list.2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py", line 115, in justice_clients
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 951, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 884, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 887, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==list.2' from '==list.2'
2021-10-01 12:26:50,269: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:26:53,091: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:26:54,350: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:26:56,173: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:26:57,271: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/profile-9.jpg
2021-10-01 12:26:57,299: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/profile-11.jpg
2021-10-01 12:26:57,311: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/profile-2.jpg
2021-10-01 12:26:57,318: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/profile-12.jpg
2021-10-01 12:26:57,327: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/preview-2.jpg
2021-10-01 12:26:57,349: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/preview-5.jpg
2021-10-01 12:26:57,384: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/preview-15.jpg
2021-10-01 12:26:57,391: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/preview-1.jpg
2021-10-01 12:26:57,412: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108698904320, Not Found: /dist/images/preview-9.jpg
2021-10-01 12:26:57,419: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/preview-8.jpg
2021-10-01 12:26:57,428: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/preview-3.jpg
2021-10-01 12:26:57,438: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108724082432, Not Found: /dist/images/preview-13.jpg
2021-10-01 12:26:57,463: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/preview-12.jpg
2021-10-01 12:26:57,475: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108724082432, Not Found: /dist/images/profile-14.jpg
2021-10-01 12:26:57,496: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/preview-11.jpg
2021-10-01 12:26:57,502: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108707297024, Not Found: /dist/images/profile-3.jpg
2021-10-01 12:26:57,519: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108724082432, Not Found: /dist/images/profile-6.jpg
2021-10-01 12:26:57,522: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/images/profile-4.jpg
2021-10-01 12:26:58,083: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /dist/json/location.json
2021-10-01 12:26:59,936: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:27:05,150: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:29:21,017: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 3876, 140108715689728, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:31:33,079: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4324, 140296918660864, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:31:34,860: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4324, 140296918660864, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:31:36,772: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4324, 140296918660864, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:31:40,212: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4324, 140296918660864, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:32:13,621: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4324, 140296885090048, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:32:17,738: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4324, 140296885090048, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:33:17,373: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4412, 140397538367232, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:33:19,054: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4412, 140397538367232, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:33:21,647: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4412, 140397538367232, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:34:11,287: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716080625408, Not Found: /dist/images/profile-12.jpg
2021-10-01 12:34:11,301: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716303910656, Not Found: /dist/images/profile-11.jpg
2021-10-01 12:34:11,314: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716072232704, Not Found: /dist/images/profile-9.jpg
2021-10-01 12:34:11,320: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716294993664, Not Found: /dist/images/profile-2.jpg
2021-10-01 12:34:11,348: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716055447296, Not Found: /dist/images/preview-5.jpg
2021-10-01 12:34:11,392: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Not Found: /dist/images/preview-2.jpg
2021-10-01 12:34:11,754: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Not Found: /dist/images/preview-9.jpg
2021-10-01 12:34:11,756: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716303910656, Not Found: /dist/images/preview-15.jpg
2021-10-01 12:34:11,788: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716294993664, Not Found: /dist/images/preview-1.jpg
2021-10-01 12:34:11,815: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716055447296, Not Found: /dist/images/profile-6.jpg
2021-10-01 12:34:11,851: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Not Found: /dist/images/profile-14.jpg
2021-10-01 12:34:11,921: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Not Found: /dist/images/preview-13.jpg
2021-10-01 12:34:11,969: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Not Found: /dist/images/preview-3.jpg
2021-10-01 12:34:12,035: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716294993664, Not Found: /dist/images/preview-8.jpg
2021-10-01 12:34:12,046: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716055447296, Not Found: /dist/images/preview-11.jpg
2021-10-01 12:34:12,171: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716294993664, Not Found: /dist/images/profile-3.jpg
2021-10-01 12:34:12,199: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716294993664, Not Found: /dist/images/profile-4.jpg
2021-10-01 12:34:12,221: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716303910656, Not Found: /dist/images/preview-12.jpg
2021-10-01 12:34:12,831: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716303910656, Not Found: /dist/json/location.json
2021-10-01 12:34:17,171: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:34:18,722: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4436, 140716063840000, Internal Server Error: /avocats_adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 251, in justice_avocats_adversaires
    avocats_adv = AvocatAdversaire.objects.annotate(
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 1056, in annotate
    clone.query.add_annotation(annotation, alias, is_summary=False)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 999, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None,
  File "/usr/lib/python3/dist-packages/django/contrib/postgres/search.py", line 62, in resolve_expression
    resolved = super().resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/usr/lib/python3/dist-packages/django/db/models/expressions.py", line 603, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/usr/lib/python3/dist-packages/django/db/models/expressions.py", line 514, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize, simple_col)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1601, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1503, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1419, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'company' into field. Choices are: adresse, cabinet, created_at, email, gsm, id, nom, observation, prenom, sexe, slug, tel, updated_at, ville
2021-10-01 12:34:38,891: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4494, 140369495815936, Internal Server Error: /avocats_adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 258, in justice_avocats_adversaires
    paginator = Paginator(avocats, AVOCAT_ADVERSARIES_PER_PAGE)
NameError: name 'avocats' is not defined
2021-10-01 12:34:56,598: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:35:02,344: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:35:04,289: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:35:06,105: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:35:31,205: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 12:36:31,619: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 13:54:27,013: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 13:54:28,666: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 4505, 139986588653312, Not Found: /adversaires/dist/images/profile-9.jpg
2021-10-01 13:55:23,258: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5268, 140550983964416, Not Found: /adversaires/dist/images/profile-9.jpg
2021-10-01 13:55:25,492: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5268, 140550983964416, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 13:55:30,155: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5268, 140550983964416, Internal Server Error: /avocats_adversaires/create
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 295, in avocat_adversaire_form
    form = AvocatAdversaireForm()
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 76, in __init__
    self.fields['type_adversaire'].widget.attrs['id'] = 'radio-switch-4'
KeyError: 'type_adversaire'
2021-10-01 13:56:12,150: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5302, 139786838947584, Not Found: /avocats_adversaires/dist/images/profile-9.jpg
2021-10-01 13:56:49,367: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5317, 140179571541760, Not Found: /avocats_adversaires/dist/images/profile-9.jpg
2021-10-01 14:01:03,845: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091318941440, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:01:12,294: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091318941440, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-10-01 14:11:08,867: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091318941440, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:11:12,482: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Not Found: /avocats_adversaires/1/dist/images/profile-9.jpg
2021-10-01 14:11:36,939: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:11:44,512: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Not Found: /avocats_adversaires/1/dist/images/profile-9.jpg
2021-10-01 14:12:15,279: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:12:19,535: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Not Found: /avocats_adversaires/dist/images/profile-9.jpg
2021-10-01 14:12:26,608: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5423, 140091087382272, Internal Server Error: /avocats_adversaires/create
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 315, in avocat_adversaire_form
    print('form.is_valid(): ', form.is_valid())
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 402, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 92, in clean_cabinet
    return self.cleaned_data['cabinet'].upper()
AttributeError: 'NoneType' object has no attribute 'upper'
2021-10-01 14:15:44,100: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026499237632, Not Found: /dist/images/profile-9.jpg
2021-10-01 14:15:44,114: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026499237632, Not Found: /dist/images/profile-12.jpg
2021-10-01 14:15:44,188: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026490320640, Not Found: /dist/images/profile-2.jpg
2021-10-01 14:15:44,191: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026260219648, Not Found: /dist/images/preview-15.jpg
2021-10-01 14:15:44,204: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026268612352, Not Found: /dist/images/preview-5.jpg
2021-10-01 14:15:44,222: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026499237632, Not Found: /dist/images/preview-2.jpg
2021-10-01 14:15:44,223: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026481927936, Not Found: /dist/images/profile-11.jpg
2021-10-01 14:15:44,264: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026260219648, Not Found: /dist/images/preview-1.jpg
2021-10-01 14:15:44,290: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026268612352, Not Found: /dist/images/preview-8.jpg
2021-10-01 14:15:44,300: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026260219648, Not Found: /dist/images/preview-3.jpg
2021-10-01 14:15:44,319: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026499237632, Not Found: /dist/images/preview-9.jpg
2021-10-01 14:15:44,334: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026268612352, Not Found: /dist/images/preview-12.jpg
2021-10-01 14:15:44,370: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026490320640, Not Found: /dist/images/profile-6.jpg
2021-10-01 14:15:44,385: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026260219648, Not Found: /dist/images/preview-13.jpg
2021-10-01 14:15:44,425: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026481927936, Not Found: /dist/images/profile-14.jpg
2021-10-01 14:15:44,432: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026260219648, Not Found: /dist/images/profile-3.jpg
2021-10-01 14:15:44,438: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026499237632, Not Found: /dist/images/profile-4.jpg
2021-10-01 14:15:44,535: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026268612352, Not Found: /dist/images/preview-11.jpg
2021-10-01 14:15:45,346: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5683, 140026268612352, Not Found: /dist/json/location.json
2021-10-01 14:17:53,480: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711047460608, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:17:57,194: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /avocats_adversaires/dist/images/profile-9.jpg
2021-10-01 14:18:07,860: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:18:13,180: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:18:23,898: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:18:30,992: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /avocats_adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:18:36,020: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /avocats_adversaires/page/1/city/Casablanca/search/dist/images/profile-9.jpg
2021-10-01 14:40:23,639: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140710997104384, Not Found: /avocats_adversaires/page/1/city/Casablanca/search/dist/images/profile-9.jpg
2021-10-01 14:40:30,469: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/profile-9.jpg
2021-10-01 14:40:30,479: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711039067904, Not Found: /dist/images/profile-2.jpg
2021-10-01 14:40:30,498: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711047460608, Not Found: /dist/images/profile-11.jpg
2021-10-01 14:40:30,687: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711039067904, Not Found: /dist/images/preview-2.jpg
2021-10-01 14:40:30,696: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711047460608, Not Found: /dist/images/preview-5.jpg
2021-10-01 14:40:30,712: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711005497088, Not Found: /dist/images/profile-12.jpg
2021-10-01 14:40:30,728: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/preview-15.jpg
2021-10-01 14:40:30,802: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /dist/images/preview-1.jpg
2021-10-01 14:40:30,902: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711039067904, Not Found: /dist/images/preview-8.jpg
2021-10-01 14:40:30,908: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711013889792, Not Found: /dist/images/preview-9.jpg
2021-10-01 14:40:30,965: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/preview-3.jpg
2021-10-01 14:40:30,988: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140710997104384, Not Found: /dist/images/preview-12.jpg
2021-10-01 14:40:31,019: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/profile-14.jpg
2021-10-01 14:40:31,030: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/preview-13.jpg
2021-10-01 14:40:31,053: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/profile-6.jpg
2021-10-01 14:40:31,075: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/preview-11.jpg
2021-10-01 14:40:31,130: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711030675200, Not Found: /dist/images/profile-3.jpg
2021-10-01 14:40:31,166: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140710997104384, Not Found: /dist/images/profile-4.jpg
2021-10-01 14:40:32,185: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140710997104384, Not Found: /dist/json/location.json
2021-10-01 14:40:36,730: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-10-01 14:40:49,351: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711013889792, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-10-01 14:40:53,594: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5768, 140711022282496, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
